apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-push
spec:
  params:
    - name: IMAGE
      type: string
  steps:
    - name: push
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      script: |
        buildah push $(params.IMAGE)